#+BEGIN_COMMENT
.. title: Don't release to Production, release to QA
.. slug: release-to-qa-not-production
.. date: 2022-11-29 14:14:25 UTC+02:00
.. tags:
.. category:
.. link:
.. description:
.. type: text
.. status: private
#+END_COMMENT

  *Automate your release workflow to such extent that the QA engineers from your team become the users of the application.*

* Introduction

  It's Friday afternoon, the end of the sprint, and a few hours before the weekend starts, and the QA engineers are performing the required tests on the last Sprint Backlog Item (SBI). The developer responsible for that item, confident that the SBI meets all acceptance criteria, is already in the weekend mood.

  Suddenly, a notification pops up --- there is an issue with the feature being tested. The developer jumps on it to see what the problem is, and after discussing with the QA engineer he/she finds out that the issue is caused by some leftover data from the previous SBI.

  Having identified the problem, the developer spends a few minutes to craft a SQL script that will clean the data, and gives it to the QA engineer. The QA engineer runs the script on the QA database, starts testing the SBI from the beginning, and then confirms that the system is "back to normal".

  Both sigh in relief while the SBI is marked as "Done" and the weekend starts. Bliss!

* Getting to the root problem

  Although the day and the sprint goal were saved, I would argue that applying the cleanup script just fixed an issue but left the root problem untouched. And to get to the root problem, let's take a closer look on what happened.

  The database issue stems from the fact that instead of being kept as close as possible to production data (as the best practices suggest) the database grew to become an entity of its own through not being kept tidy by the team.

  When testing a SBI involves changing some of the data from the database, it is not very often that those changes are reverted as soon as the SBI leaves the QA environment. With each such change the two databases (production and QA) grow further and further apart, and the probability of having to apply a workaround script increases each time. However  the paradox is that the cleanup script, although it solves the issue, is /yet another change to the data/ which widens even more the gap between QA and production databases.

  And there lies our problem: not within the workaround script itself, but within the practice of applying workarounds to patch the proverbial broken pipes instead of building actual deployment pipelines.

  But this problem goes one level deeper; sure, we can fix the problem at hand by restoring the database from a production backup but to solve the issue once and for all we need to change how we look at QA environment.

  But our root-cause analysis is not complete yet. We can't just say "let's never apply workarounds" because workarounds are some sort of necessary evil. Let's look at why that is, shall we?

* Why and when do we apply workarounds in production?

  In Production environment a workaround is applied /only in critical situations/ due to high risk of breaking the running system by making ad-hoc changes to it.

  Unlike the QA environment where, when the system breaks only a few users are affected --- namely the QA engineers, when the system halts in Production the costs of the downtime are much, much higher. An improper or forgotten =where= condition in a delete script which wipes out whole tables of data, and renders the system unusable, in the happiest case will lead only to frustrated customers that can't use the thing they paid for.

  As such, in every critical situation first and foremost comes the assessment: is a workaround really needed?

  When the answer is yes (i.e., there is no other way of fixing the issue now), then /usually/ there are some procedures to follow. Sticking with the database script example, the minimal procedure would be to:
  1. create the workaround script,
  2. have that script /reviewed and approved by at least one additional person/, and
  3. have the script executed on Production by someone with proper access rights.

  OK, now we're settled: workarounds are necessary /in critical situations/, and are applied after /assessment/, /review/, and /approval/. Then, going back to our story, the following question arises:

* Why do we apply workarounds in QA environment?

  QA environment is isolated from Production environment, and by definition it has way fewer users. Furthermore, those users have a lot of technical knowledge of how the system runs, and always have something else to do (like designing/writing test cases) while the system is being brought to normal again.

  Looking from this point of view, there is almost never a /critical/ situation that would require applying a workaround in QA environment.

  Sure, missing the sprint goal may seem like a critical situation because commitments are important. But on the other hand, and going back to our example --- if we're applying a workaround in QA just to promote some feature towards Production, are we /really/ sure that the feature is ready?

  Now that the assessment of criticality is done, let's get back to our topic and ask:

* What if we treated QA environment like Production?

  Production and QA environments are different (/very/ different I may add); there's no doubt about that. What makes them different, from the point of view of our topic, is the fact that when a feature is deployed in Production environment, /all/ the prerequisites are known, and all preliminary steps are executed.

  On the other hand, when deploying to QA environment we don't always have this knowledge, nor do we have all the preliminary steps completed at all times. Furthermore, deploying on QA may require additional steps than on Production, e.g.: restoring the database to the last backup from Production, data anonymization etc.

  But the difference between the number of unknowns can be compensated by the difference between number of deployments, and the fact that a failure in QA environment is not critical. In other words, what we lack in knowledge when deploying to QA environment can be compensated by multiple deployment trials, where each deployment trial gets closer and closer to success.

  And when it comes to doing repetitive tasks...

* Automation is key

  To alleviate the difference between (successive) environments you only need to do one thing, although I must say from the start that achieving that one thing /can be really hard/ --- *automate everything*.

  If a release workflow is properly (read /fully/) automated, then the difference between various environments is reduced mainly to:
  - The group of people who have proper access rights to run the workflow on the specific environment. With today's' tools on the market the difference becomes simplified further --- it is in the group of people that are allowed to see or to push the "Deploy" button.
  - The number and order of "Deploy" buttons a person has to push for the deploy to succeed.

  Although we strive to have our environments behave all the same, they are still inherently different. As such, it goes without saying that not everyone may have rights to deploy to Production, and --- due to some constraints --- on some environment there may be additional actions required to deploy. Nonetheless, the objective remains the same: /avoid manual intervention as much as possible/.

* The Snowball Effect

  Once achieved, the effects of this objective of having minimal manual intervention ripple through and start a [[https://en.wikipedia.org/wiki/Snowball_effect][snowball effect]].

** Efficiency

  At first, you gain efficiency --- there is no checklist to go through when deploying, no time needed to spend doing the tedious steps of deployment; the computers will perform those steps as quickly as possible and /always/ in the same order without skipping any of them or making the errors that humans usually do when performing tedious work.

  With a click of a button, or on a certain event the deployment starts and while it runs the people from the team are free to do whatever they want in the time it takes to deploy: they can have a cup of coffee, can make small talk with a colleague, or can mind the more important business like the overall quality of the product they're working on.

** Speed

  Furthermore, besides efficiency you can gain speed --- just by delegating the deployment process to computers you gain time because computers do boring stuff a lot quicker than humans.

  With efficiency and speed comes reduced [[https://martinfowler.com/articles/branching-patterns.html#integration-friction][integration friction]]. A common effect of reduced integration friction is an increase in integration frequency. High integration frequency coupled with workflow automation leads to an increase in the number of deployments that are made.

  And this is where the magic unravels.

** Tight feedback loop

   Once you automate the repetitive tasks you free-up the time of the QA engineer, which allows him/her to spend more time with the system(s) they are testing. In other words, the time gained through workflow automation is invested into the actual Quality Assurance of the system under test.

   And when the QA engineer invests more time into the testing process, he/she will be able to spot more issues. With enough repetitions enabled by quick deployments, the QA engineer acquires a certain amount of skills which will enable him/her to spot defects faster. The sooner a defect is spotted, the sooner it is reported, and subsequently, the sooner it gets fixed.

   We have a name for this thing --- it's called a /feedback loop/. The feedback loop is not introduced by automation --- it was long present in the project, but once workflow automation is introduced it tightens the feedback loop, which means we, as developers, have to wait less time to see the effects of the changes we introduced into the system. In our specific case, we have to wait less because workflow automation reduces the time of the deployment to QA environment to minimum.

** Improved user experience

   But wait, there's more! The time that the QA engineer gets to invest into growing his/her skills is spent using the system under test. With more time spent using the system under test, the QA engineer gets closer and closer to the mindset of the real users of the system. And while in this mindset, the QA engineer not only understands what the system does for the user but also understands what the user wants to do.

   Of course, this understanding is bound by a certain maximum but nonetheless, the effect it has on the development process is enormous.

   First and foremost, there is an increase in the quality of the system: when the QA engineers have a sound understanding of what the user wants to do they will make sure that the system indeed caters to the needs of its users. This in itself is a huge win for the users alone but this also benefits the entire team --- the knowledge about the system gets disseminated within the whole team (including developers), and the Product Owner (PO) is not  the bottleneck anymore.

   Furthermore, with more time spent in the mindset of a user, the QA engineer will start striving for an improved user experience because he/she, like the real users of the system, will strive to do thing faster.

   As such, the QA engineer starts suggesting some usability improvements of the system. These improvements are small --- e.g., change the order of the menu items, add the ability to have custom shortcuts on the homepage etc, but they do improve the experience of the user.

   Sure, all of those changes must be  discussed with the team /and/ approved by the PO but those who get approved bring the system closer to what the /actual users/ want.

* Allow the QA engineer to be an user of the system

   The main role of a QA engineer is to ensure that the system under test satisfies the needs of its users. As such, the QA engineer needs to think like a user, to act like a user, and to be able to quickly shift from the mindset of the user to the mindset of the problem analyst required by the job description.

  But if you take from the QA engineer all the hassle of deployment and fiddling with making the system run properly in the testing environment you are unlocking more time for him/her to spend in the mindset of an actual user, and having a user of the system close by is a treasure trove for building it in such a way that the system accomplishes its purpose --- catering to the needs of his users.

   As a developer, it may be strange to look at your colleague --- the QA engineer --- like at an user of the system you're both working on. After all, you both know a lot more of what's under the hood of that system for any of you to be considered just a simple user of it.

   But it is a change worth making. And, as the saying goes, to change the world you need to start with changing yourself. This change comes when you treat QA environment as production environment and make all the efforts needed to uphold the delivery to QA to the same rigor as delivery to production. In essence, it's nothing but a shift in the mindset that was already mentioned in the title --- don't release to Production, release to QA.
